version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - my-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
